### ISSUE TITLE
I also did something like this

### ISSUE THREAD

**Issue by eboatwright** [l2wilson94/Frogasaurus#2]
That's funny, I also made a script like this! (Though it was in Ruby) I had a ruby file that would be run via an editor extension whenever I saved the file and it would compile it all into one .js file

**Comment by TodePond** [comment]
Nice one! :) I really wanted a way of making my libraries work in different environments - but with a really lightweight + simple bundler, so that's where frogasaurus came from :D

**Comment by eboatwright** [comment]
Yeah that's awesome! (P.S. I wasn't accusing you of anything, as I didn't even post it anywhere, I just thought it was cool :smile:)

**Comment by TodePond** [comment]
Oh no not at all :D It's cool to hear! and to share experiences! :)

**Comment by eboatwright** [comment]
Yep yep! :tada:
